#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimBP_MIS_OccupationBase

#include "Basic.hpp"

#include "AnimBP_MIS_OccupationBase_classes.hpp"
#include "AnimBP_MIS_OccupationBase_parameters.hpp"


namespace SDK
{

// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink                        AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UAnimBP_MIS_OccupationBase_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "AnimGraph");

	Params::AnimBP_MIS_OccupationBase_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_MIS_OccupationBase_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "BlueprintUpdateAnimation");

	Params::AnimBP_MIS_OccupationBase_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_1B90CB474EADD886D1C824B813B23E88
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_1B90CB474EADD886D1C824B813B23E88()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_1B90CB474EADD886D1C824B813B23E88");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_43C020E842A7F5F5466D0CB50301C295
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_43C020E842A7F5F5466D0CB50301C295()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_43C020E842A7F5F5466D0CB50301C295");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_6857E6CC42B9B2DE3F27EFB3A363B63F
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_6857E6CC42B9B2DE3F27EFB3A363B63F()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_6857E6CC42B9B2DE3F27EFB3A363B63F");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_68DFD47846B64452B9A04D90BAFC33B9
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_68DFD47846B64452B9A04D90BAFC33B9()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_68DFD47846B64452B9A04D90BAFC33B9");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9BC6686B462927ED9A2C98B7E93A4F49
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9BC6686B462927ED9A2C98B7E93A4F49()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9BC6686B462927ED9A2C98B7E93A4F49");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9E0B124A417AFDA57654B6BE8F80284C
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9E0B124A417AFDA57654B6BE8F80284C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_9E0B124A417AFDA57654B6BE8F80284C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_A5256B8B460D35F26C528C967F661F3C
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_A5256B8B460D35F26C528C967F661F3C()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_A5256B8B460D35F26C528C967F661F3C");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_D9E4B9784AB078F33ABC708206698198
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_D9E4B9784AB078F33ABC708206698198()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_D9E4B9784AB078F33ABC708206698198");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_FD3A4C0F44BFEDF0CBD25680C4B24C22
// (BlueprintEvent)

void UAnimBP_MIS_OccupationBase_C::EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_FD3A4C0F44BFEDF0CBD25680C4B24C22()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_AnimBP_MIS_OccupationBase_AnimGraphNode_TransitionResult_FD3A4C0F44BFEDF0CBD25680C4B24C22");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AnimBP_MIS_OccupationBase.AnimBP_MIS_OccupationBase_C.ExecuteUbergraph_AnimBP_MIS_OccupationBase
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAnimBP_MIS_OccupationBase_C::ExecuteUbergraph_AnimBP_MIS_OccupationBase(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AnimBP_MIS_OccupationBase_C", "ExecuteUbergraph_AnimBP_MIS_OccupationBase");

	Params::AnimBP_MIS_OccupationBase_C_ExecuteUbergraph_AnimBP_MIS_OccupationBase Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

