#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AnimnotifyOption

#include "Basic.hpp"


namespace SDK
{

// UserDefinedStruct AnimnotifyOption.AnimnotifyOption
// 0x0001 (0x0001 - 0x0000)
struct FAnimnotifyOption final
{
public:
	bool                                          IsRangeWP__10_735D2157402E68251ED8E580CDCF0944;    // 0x0000(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
};
static_assert(alignof(FAnimnotifyOption) == 0x000001, "Wrong alignment on FAnimnotifyOption");
static_assert(sizeof(FAnimnotifyOption) == 0x000001, "Wrong size on FAnimnotifyOption");
static_assert(offsetof(FAnimnotifyOption, IsRangeWP__10_735D2157402E68251ED8E580CDCF0944) == 0x000000, "Member 'FAnimnotifyOption::IsRangeWP__10_735D2157402E68251ED8E580CDCF0944' has a wrong offset!");

}

