#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AudioZoneBox

#include "Basic.hpp"

#include "BP_AudioZoneBox_classes.hpp"
#include "BP_AudioZoneBox_parameters.hpp"


namespace SDK
{

// Function BP_AudioZoneBox.BP_AudioZoneBox_C.ActiveIndoor?
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ActiveIndoor__0                                        (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::ActiveIndoor_(bool* ActiveIndoor__0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "ActiveIndoor?");

	Params::BP_AudioZoneBox_C_ActiveIndoor_ Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ActiveIndoor__0 != nullptr)
		*ActiveIndoor__0 = Parms.ActiveIndoor__0;
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BndEvt__BP_AudioZoneBox_AreaMesh_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::BndEvt__BP_AudioZoneBox_AreaMesh_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BndEvt__BP_AudioZoneBox_AreaMesh_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature");

	Params::BP_AudioZoneBox_C_BndEvt__BP_AudioZoneBox_AreaMesh_K2Node_ComponentBoundEvent_3_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BndEvt__BP_AudioZoneBox_Visualize_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FHitResult                       SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABP_AudioZoneBox_C::BndEvt__BP_AudioZoneBox_Visualize_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BndEvt__BP_AudioZoneBox_Visualize_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BP_AudioZoneBox_C_BndEvt__BP_AudioZoneBox_Visualize_K2Node_ComponentBoundEvent_2_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BP_EnvZoneActiveByPlayer
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::BP_EnvZoneActiveByPlayer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BP_EnvZoneActiveByPlayer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BP_EnvZoneDiscard
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::BP_EnvZoneDiscard()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BP_EnvZoneDiscard");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.Bp_EnvZoneEnter
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AudioZoneBox_C*               OverlapedZone                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::Bp_EnvZoneEnter(class ABP_AudioZoneBox_C* OverlapedZone)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "Bp_EnvZoneEnter");

	Params::BP_AudioZoneBox_C_Bp_EnvZoneEnter Parms{};

	Parms.OverlapedZone = OverlapedZone;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BP_EnvZoneInitActive
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::BP_EnvZoneInitActive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BP_EnvZoneInitActive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BP_EnvZoneLeave
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AudioZoneBox_C*               LeaveZone                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::BP_EnvZoneLeave(class ABP_AudioZoneBox_C* LeaveZone)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BP_EnvZoneLeave");

	Params::BP_AudioZoneBox_C_BP_EnvZoneLeave Parms{};

	Parms.LeaveZone = LeaveZone;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BpAkZone3dBaseRepeat
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkAudioEvent*                    RepeatAkEvent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::BpAkZone3dBaseRepeat(class UAkAudioEvent* RepeatAkEvent, double Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BpAkZone3dBaseRepeat");

	Params::BP_AudioZoneBox_C_BpAkZone3dBaseRepeat Parms{};

	Parms.RepeatAkEvent = RepeatAkEvent;
	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BpAkZone3dSecodryRepeat
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkAudioEvent*                    RepeatAkEvent                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  Delay                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::BpAkZone3dSecodryRepeat(class UAkAudioEvent* RepeatAkEvent, double Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BpAkZone3dSecodryRepeat");

	Params::BP_AudioZoneBox_C_BpAkZone3dSecodryRepeat Parms{};

	Parms.RepeatAkEvent = RepeatAkEvent;
	Parms.Delay = Delay;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.BpSpawnDirecEnvEventStart
// (BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::BpSpawnDirecEnvEventStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "BpSpawnDirecEnvEventStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.CalculateAttenuate
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::CalculateAttenuate()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "CalculateAttenuate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.CollisionAcitive
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::CollisionAcitive()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "CollisionAcitive");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.EnableAkComponentsTick
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bEnable                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::EnableAkComponentsTick(bool bEnable)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "EnableAkComponentsTick");

	Params::BP_AudioZoneBox_C_EnableAkComponentsTick Parms{};

	Parms.bEnable = bEnable;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.ExecuteUbergraph_BP_AudioZoneBox
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::ExecuteUbergraph_BP_AudioZoneBox(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "ExecuteUbergraph_BP_AudioZoneBox");

	Params::BP_AudioZoneBox_C_ExecuteUbergraph_BP_AudioZoneBox Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.FillAllOverlappedZonesAsSlave
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::FillAllOverlappedZonesAsSlave()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "FillAllOverlappedZonesAsSlave");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.FindAmbienceSpotPoint
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::FindAmbienceSpotPoint()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "FindAmbienceSpotPoint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.GetHighestPriorityMaster
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ABP_AudioZoneBox_C*               ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, NoDestructor, HasGetValueTypeHash)

class ABP_AudioZoneBox_C* ABP_AudioZoneBox_C::GetHighestPriorityMaster()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "GetHighestPriorityMaster");

	Params::BP_AudioZoneBox_C_GetHighestPriorityMaster Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.IsIntersect
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FBox                             A                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// struct FBox                             B                                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
// bool                                    bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::IsIntersect(const struct FBox& A, const struct FBox& B, bool* bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "IsIntersect");

	Params::BP_AudioZoneBox_C_IsIntersect Parms{};

	Parms.A = std::move(A);
	Parms.B = std::move(B);

	UObject::ProcessEvent(Func, &Parms);

	if (bResult != nullptr)
		*bResult = Parms.bResult;
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.NotifyOcclusionToSlave
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bActivated                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::NotifyOcclusionToSlave(bool bActivated)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "NotifyOcclusionToSlave");

	Params::BP_AudioZoneBox_C_NotifyOcclusionToSlave Parms{};

	Parms.bActivated = bActivated;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.OnMyPlayerEnter
// (BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::OnMyPlayerEnter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "OnMyPlayerEnter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_AudioZoneBox_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.Reverb_param
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::Reverb_param()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "Reverb_param");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.setReverb
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::SetReverb()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "setReverb");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.Spawn3dEnvEvent
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkAudioEvent*                    AkEvent                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent*                    PlayedAk                                               (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  Delay                                                  (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::Spawn3dEnvEvent(class UAkAudioEvent* AkEvent, class UAkAudioEvent** PlayedAk, double* Delay)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "Spawn3dEnvEvent");

	Params::BP_AudioZoneBox_C_Spawn3dEnvEvent Parms{};

	Parms.AkEvent = AkEvent;

	UObject::ProcessEvent(Func, &Parms);

	if (PlayedAk != nullptr)
		*PlayedAk = Parms.PlayedAk;

	if (Delay != nullptr)
		*Delay = Parms.Delay;
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.UpdateMasterOcclusionZones
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_AudioZoneBox_C*               InMaster                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// bool                                    bAdd                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_AudioZoneBox_C::UpdateMasterOcclusionZones(const class ABP_AudioZoneBox_C*& InMaster, bool bAdd)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "UpdateMasterOcclusionZones");

	Params::BP_AudioZoneBox_C_UpdateMasterOcclusionZones Parms{};

	Parms.InMaster = InMaster;
	Parms.bAdd = bAdd;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AudioZoneBox.BP_AudioZoneBox_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_AudioZoneBox_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AudioZoneBox_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}

}

