#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AssetManager

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_AssetManager.BP_AssetManager_C
// 0x0000 (0x0A70 - 0x0A70)
class UBP_AssetManager_C final : public UM1AssetManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_AssetManager_C">();
	}
	static class UBP_AssetManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AssetManager_C>();
	}
};
static_assert(alignof(UBP_AssetManager_C) == 0x000008, "Wrong alignment on UBP_AssetManager_C");
static_assert(sizeof(UBP_AssetManager_C) == 0x000A70, "Wrong size on UBP_AssetManager_C");

}

