#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FieldInteractableBase_Hit

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_FieldInteractableBase_Hit.BP_FieldInteractableBase_Hit_C
// 0x0000 (0x0448 - 0x0448)
class ABP_FieldInteractableBase_Hit_C : public AM1FieldInteractableActor_Hit
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_FieldInteractableBase_Hit_C">();
	}
	static class ABP_FieldInteractableBase_Hit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FieldInteractableBase_Hit_C>();
	}
};
static_assert(alignof(ABP_FieldInteractableBase_Hit_C) == 0x000008, "Wrong alignment on ABP_FieldInteractableBase_Hit_C");
static_assert(sizeof(ABP_FieldInteractableBase_Hit_C) == 0x000448, "Wrong size on ABP_FieldInteractableBase_Hit_C");

}

