#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionTaskMove

#include "Basic.hpp"

#include "BP_MissionTaskMove_classes.hpp"
#include "BP_MissionTaskMove_parameters.hpp"


namespace SDK
{

// Function BP_MissionTaskMove.BP_MissionTaskMove_C.ExecuteUbergraph_BP_MissionTaskMove
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MissionTaskMove_C::ExecuteUbergraph_BP_MissionTaskMove(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MissionTaskMove_C", "ExecuteUbergraph_BP_MissionTaskMove");

	Params::BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MissionTaskMove.BP_MissionTaskMove_C.TaskActorStateChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// EM1EventActorState                      InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MissionTaskMove_C::TaskActorStateChanged(EM1EventActorState InState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MissionTaskMove_C", "TaskActorStateChanged");

	Params::BP_MissionTaskMove_C_TaskActorStateChanged Parms{};

	Parms.InState = InState;

	UObject::ProcessEvent(Func, &Parms);
}

}

