#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionTaskMove

#include "Basic.hpp"

#include "M1_structs.hpp"


namespace SDK::Params
{

// Function BP_MissionTaskMove.BP_MissionTaskMove_C.ExecuteUbergraph_BP_MissionTaskMove
// 0x0008 (0x0008 - 0x0000)
struct BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1EventActorState                            K2Node_Event_InState;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove) == 0x000004, "Wrong alignment on BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove");
static_assert(sizeof(BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove) == 0x000008, "Wrong size on BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove");
static_assert(offsetof(BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove, EntryPoint) == 0x000000, "Member 'BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove, K2Node_Event_InState) == 0x000004, "Member 'BP_MissionTaskMove_C_ExecuteUbergraph_BP_MissionTaskMove::K2Node_Event_InState' has a wrong offset!");

// Function BP_MissionTaskMove.BP_MissionTaskMove_C.TaskActorStateChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_MissionTaskMove_C_TaskActorStateChanged final
{
public:
	EM1EventActorState                            InState;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_MissionTaskMove_C_TaskActorStateChanged) == 0x000001, "Wrong alignment on BP_MissionTaskMove_C_TaskActorStateChanged");
static_assert(sizeof(BP_MissionTaskMove_C_TaskActorStateChanged) == 0x000001, "Wrong size on BP_MissionTaskMove_C_TaskActorStateChanged");
static_assert(offsetof(BP_MissionTaskMove_C_TaskActorStateChanged, InState) == 0x000000, "Member 'BP_MissionTaskMove_C_TaskActorStateChanged::InState' has a wrong offset!");

}

