#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MissionTaskContinuousSurvival

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_MissionTaskContinuousSurvival.BP_MissionTaskContinuousSurvival_C
// 0x0010 (0x06F8 - 0x06E8)
class ABP_MissionTaskContinuousSurvival_C final : public AM1MissionTaskActorWaveSurvival
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBillboardComponent*                    Billboard;                                         // 0x06F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_MissionTaskContinuousSurvival(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_MissionTaskContinuousSurvival_C">();
	}
	static class ABP_MissionTaskContinuousSurvival_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_MissionTaskContinuousSurvival_C>();
	}
};
static_assert(alignof(ABP_MissionTaskContinuousSurvival_C) == 0x000008, "Wrong alignment on ABP_MissionTaskContinuousSurvival_C");
static_assert(sizeof(ABP_MissionTaskContinuousSurvival_C) == 0x0006F8, "Wrong size on ABP_MissionTaskContinuousSurvival_C");
static_assert(offsetof(ABP_MissionTaskContinuousSurvival_C, UberGraphFrame) == 0x0006E8, "Member 'ABP_MissionTaskContinuousSurvival_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_MissionTaskContinuousSurvival_C, Billboard) == 0x0006F0, "Member 'ABP_MissionTaskContinuousSurvival_C::Billboard' has a wrong offset!");

}

