#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerNpcBase

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_PlayerNpcBase.BP_PlayerNpcBase_C
// 0x0030 (0x0860 - 0x0830)
class ABP_PlayerNpcBase_C : public AM1PlayerNpc
{
public:
	class UAK_Dialog_Component_C*                 AK_Dialog_Component;                               // 0x0830(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1InteractionInvokerComponent*         M1InteractionInvoker;                              // 0x0838(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UM1IndicatorComponent*                  M1Indicator;                                       // 0x0840(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Origin_position;                                   // 0x0848(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Sub_position;                                      // 0x0854(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	class UM1InteractionInvokerComponent* BP_GetInteractionComponent() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_PlayerNpcBase_C">();
	}
	static class ABP_PlayerNpcBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlayerNpcBase_C>();
	}
};
static_assert(alignof(ABP_PlayerNpcBase_C) == 0x000010, "Wrong alignment on ABP_PlayerNpcBase_C");
static_assert(sizeof(ABP_PlayerNpcBase_C) == 0x000860, "Wrong size on ABP_PlayerNpcBase_C");
static_assert(offsetof(ABP_PlayerNpcBase_C, AK_Dialog_Component) == 0x000830, "Member 'ABP_PlayerNpcBase_C::AK_Dialog_Component' has a wrong offset!");
static_assert(offsetof(ABP_PlayerNpcBase_C, M1InteractionInvoker) == 0x000838, "Member 'ABP_PlayerNpcBase_C::M1InteractionInvoker' has a wrong offset!");
static_assert(offsetof(ABP_PlayerNpcBase_C, M1Indicator) == 0x000840, "Member 'ABP_PlayerNpcBase_C::M1Indicator' has a wrong offset!");
static_assert(offsetof(ABP_PlayerNpcBase_C, Origin_position) == 0x000848, "Member 'ABP_PlayerNpcBase_C::Origin_position' has a wrong offset!");
static_assert(offsetof(ABP_PlayerNpcBase_C, Sub_position) == 0x000854, "Member 'ABP_PlayerNpcBase_C::Sub_position' has a wrong offset!");

}

