#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ServerStreamingAreaActor

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ServerStreamingAreaActor.BP_ServerStreamingAreaActor_C
// 0x0008 (0x0278 - 0x0270)
class ABP_ServerStreamingAreaActor_C final : public AM1ServerStreamingAreaActor
{
public:
	class UBillboardComponent*                    Billboard;                                         // 0x0270(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_ServerStreamingAreaActor_C">();
	}
	static class ABP_ServerStreamingAreaActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ServerStreamingAreaActor_C>();
	}
};
static_assert(alignof(ABP_ServerStreamingAreaActor_C) == 0x000008, "Wrong alignment on ABP_ServerStreamingAreaActor_C");
static_assert(sizeof(ABP_ServerStreamingAreaActor_C) == 0x000278, "Wrong size on ABP_ServerStreamingAreaActor_C");
static_assert(offsetof(ABP_ServerStreamingAreaActor_C, Billboard) == 0x000270, "Member 'ABP_ServerStreamingAreaActor_C::Billboard' has a wrong offset!");

}

