#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TaskEvent_Camp

#include "Basic.hpp"

#include "BP_TaskEvent_Camp_classes.hpp"
#include "BP_TaskEvent_Camp_parameters.hpp"


namespace SDK
{

// Function BP_TaskEvent_Camp.BP_TaskEvent_Camp_C.ExecuteUbergraph_BP_TaskEvent_Camp
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TaskEvent_Camp_C::ExecuteUbergraph_BP_TaskEvent_Camp(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TaskEvent_Camp_C", "ExecuteUbergraph_BP_TaskEvent_Camp");

	Params::BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_TaskEvent_Camp.BP_TaskEvent_Camp_C.BP_ActivateEntryPoint
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bPlayActivateAnimation                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_TaskEvent_Camp_C::BP_ActivateEntryPoint(bool bPlayActivateAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_TaskEvent_Camp_C", "BP_ActivateEntryPoint");

	Params::BP_TaskEvent_Camp_C_BP_ActivateEntryPoint Parms{};

	Parms.bPlayActivateAnimation = bPlayActivateAnimation;

	UObject::ProcessEvent(Func, &Parms);
}

}

