#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_TaskEvent_Camp

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_TaskEvent_Camp.BP_TaskEvent_Camp_C.ExecuteUbergraph_BP_TaskEvent_Camp
// 0x0040 (0x0040 - 0x0000)
struct BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bPlayActivateAnimation;               // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_CampTank_C*                         K2Node_DynamicCast_AsBP_Camp_Tank;                 // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABP_CampSimple_C*                       K2Node_DynamicCast_AsBP_Camp_Simple;               // 0x0028(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp) == 0x000008, "Wrong alignment on BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp");
static_assert(sizeof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp) == 0x000040, "Wrong size on BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, EntryPoint) == 0x000000, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::EntryPoint' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, Temp_int_Array_Index_Variable) == 0x000004, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, K2Node_Event_bPlayActivateAnimation) == 0x000008, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::K2Node_Event_bPlayActivateAnimation' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, Temp_int_Loop_Counter_Variable) == 0x00000C, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, CallFunc_Array_Get_Item) == 0x000010, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, K2Node_DynamicCast_AsBP_Camp_Tank) == 0x000018, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::K2Node_DynamicCast_AsBP_Camp_Tank' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, K2Node_DynamicCast_AsBP_Camp_Simple) == 0x000028, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::K2Node_DynamicCast_AsBP_Camp_Simple' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, K2Node_DynamicCast_bSuccess_1) == 0x000030, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, CallFunc_Add_IntInt_ReturnValue) == 0x000034, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, CallFunc_Array_Length_ReturnValue) == 0x000038, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'BP_TaskEvent_Camp_C_ExecuteUbergraph_BP_TaskEvent_Camp::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function BP_TaskEvent_Camp.BP_TaskEvent_Camp_C.BP_ActivateEntryPoint
// 0x0001 (0x0001 - 0x0000)
struct BP_TaskEvent_Camp_C_BP_ActivateEntryPoint final
{
public:
	bool                                          bPlayActivateAnimation;                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_TaskEvent_Camp_C_BP_ActivateEntryPoint) == 0x000001, "Wrong alignment on BP_TaskEvent_Camp_C_BP_ActivateEntryPoint");
static_assert(sizeof(BP_TaskEvent_Camp_C_BP_ActivateEntryPoint) == 0x000001, "Wrong size on BP_TaskEvent_Camp_C_BP_ActivateEntryPoint");
static_assert(offsetof(BP_TaskEvent_Camp_C_BP_ActivateEntryPoint, bPlayActivateAnimation) == 0x000000, "Member 'BP_TaskEvent_Camp_C_BP_ActivateEntryPoint::bPlayActivateAnimation' has a wrong offset!");

}

