#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VoidVaultStabilizer

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_VoidVaultStabilizer.BP_VoidVaultStabilizer_C.BP_IsPickableContainer
// 0x0001 (0x0001 - 0x0000)
struct BP_VoidVaultStabilizer_C_BP_IsPickableContainer final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_VoidVaultStabilizer_C_BP_IsPickableContainer) == 0x000001, "Wrong alignment on BP_VoidVaultStabilizer_C_BP_IsPickableContainer");
static_assert(sizeof(BP_VoidVaultStabilizer_C_BP_IsPickableContainer) == 0x000001, "Wrong size on BP_VoidVaultStabilizer_C_BP_IsPickableContainer");
static_assert(offsetof(BP_VoidVaultStabilizer_C_BP_IsPickableContainer, ReturnValue) == 0x000000, "Member 'BP_VoidVaultStabilizer_C_BP_IsPickableContainer::ReturnValue' has a wrong offset!");

}

