#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BR

#include "Basic.hpp"

#include "UpperBody_structs.hpp"


namespace SDK
{

// ScriptStruct BR.BR_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct BR::FAnimBlueprintGeneratedConstantData : public UpperBody::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(BR::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on BR::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(BR::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on BR::FAnimBlueprintGeneratedConstantData");

}

