#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcGleyNosferatuDamage

#include "Basic.hpp"

#include "CalcDamageBase_classes.hpp"
#include "M1Data_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CalcGleyNosferatuDamage.CalcGleyNosferatuDamage_C
// 0x0008 (0x0138 - 0x0130)
class UCalcGleyNosferatuDamage_C final : public UCalcDamageBase_C
{
public:
	double                                        ATKMultiplierByCharge;                             // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DoCalculation(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;
	void SetAdditionalDamageInfo(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;
	void SumATK(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CalcGleyNosferatuDamage_C">();
	}
	static class UCalcGleyNosferatuDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalcGleyNosferatuDamage_C>();
	}
};
static_assert(alignof(UCalcGleyNosferatuDamage_C) == 0x000008, "Wrong alignment on UCalcGleyNosferatuDamage_C");
static_assert(sizeof(UCalcGleyNosferatuDamage_C) == 0x000138, "Wrong size on UCalcGleyNosferatuDamage_C");
static_assert(offsetof(UCalcGleyNosferatuDamage_C, ATKMultiplierByCharge) == 0x000130, "Member 'UCalcGleyNosferatuDamage_C::ATKMultiplierByCharge' has a wrong offset!");

}

