#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CalcTargetHPRatioDamage

#include "Basic.hpp"

#include "CalcDamageBase_classes.hpp"
#include "M1Data_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass CalcTargetHPRatioDamage.CalcTargetHPRatioDamage_C
// 0x0018 (0x0148 - 0x0130)
class UCalcTargetHPRatioDamage_C final : public UCalcDamageBase_C
{
public:
	double                                        TargetHpBasedDamage;                               // 0x0130(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetNamedHpBasedDamage;                          // 0x0138(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TargetBossHpBasedDamage;                           // 0x0140(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void DoCalculation(struct FM1AbilityOpCalcParam& Param, struct FM1CalcDamageInfo& DamageInfo) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CalcTargetHPRatioDamage_C">();
	}
	static class UCalcTargetHPRatioDamage_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCalcTargetHPRatioDamage_C>();
	}
};
static_assert(alignof(UCalcTargetHPRatioDamage_C) == 0x000008, "Wrong alignment on UCalcTargetHPRatioDamage_C");
static_assert(sizeof(UCalcTargetHPRatioDamage_C) == 0x000148, "Wrong size on UCalcTargetHPRatioDamage_C");
static_assert(offsetof(UCalcTargetHPRatioDamage_C, TargetHpBasedDamage) == 0x000130, "Member 'UCalcTargetHPRatioDamage_C::TargetHpBasedDamage' has a wrong offset!");
static_assert(offsetof(UCalcTargetHPRatioDamage_C, TargetNamedHpBasedDamage) == 0x000138, "Member 'UCalcTargetHPRatioDamage_C::TargetNamedHpBasedDamage' has a wrong offset!");
static_assert(offsetof(UCalcTargetHPRatioDamage_C, TargetBossHpBasedDamage) == 0x000140, "Member 'UCalcTargetHPRatioDamage_C::TargetBossHpBasedDamage' has a wrong offset!");

}

