#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_SR_1003

#include "Basic.hpp"

#include "F_SR_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass F_SR_1003.F_SR_1003_C
// 0x0000 (0x1C80 - 0x1C80)
class UF_SR_1003_C final : public UF_SR_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"F_SR_1003_C">();
	}
	static class UF_SR_1003_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UF_SR_1003_C>();
	}
};
static_assert(alignof(UF_SR_1003_C) == 0x000010, "Wrong alignment on UF_SR_1003_C");
static_assert(sizeof(UF_SR_1003_C) == 0x001C80, "Wrong size on UF_SR_1003_C");

}

