#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_TR

#include "Basic.hpp"

#include "UpperBody_structs.hpp"


namespace SDK
{

// ScriptStruct F_TR.F_TR_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x01F0 - 0x01F0)
struct F_TR::FAnimBlueprintGeneratedConstantData : public UpperBody::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(F_TR::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on F_TR::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(F_TR::FAnimBlueprintGeneratedConstantData) == 0x0001F0, "Wrong size on F_TR::FAnimBlueprintGeneratedConstantData");

}

