#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FSR3MovieRenderPipeline

#include "Basic.hpp"


namespace SDK
{

// Enum FSR3MovieRenderPipeline.EFSR3MoviePipelineQuality
// NumValues: 0x0007
enum class EFSR3MoviePipelineQuality : uint8
{
	Unused                                   = 0,
	Native                                   = 1,
	Quality                                  = 2,
	Balanced                                 = 3,
	Performance                              = 4,
	UltraPerformance                         = 5,
	EFSR3MoviePipelineQuality_MAX            = 6,
};

}

