#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MOB_CMN_1002_A001_Soulless

#include "Basic.hpp"

#include "NormalMonsterBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MOB_CMN_1002_A001_Soulless.MOB_CMN_1002_A001_Soulless_C
// 0x0000 (0x0D50 - 0x0D50)
class AMOB_CMN_1002_A001_Soulless_C final : public ANormalMonsterBase_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MOB_CMN_1002_A001_Soulless_C">();
	}
	static class AMOB_CMN_1002_A001_Soulless_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMOB_CMN_1002_A001_Soulless_C>();
	}
};
static_assert(alignof(AMOB_CMN_1002_A001_Soulless_C) == 0x000010, "Wrong alignment on AMOB_CMN_1002_A001_Soulless_C");
static_assert(sizeof(AMOB_CMN_1002_A001_Soulless_C) == 0x000D50, "Wrong size on AMOB_CMN_1002_A001_Soulless_C");

}

