#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MultiplyMoveSpeed

#include "Basic.hpp"

#include "M1_structs.hpp"
#include "M1Data_structs.hpp"


namespace SDK::Params
{

// Function MultiplyMoveSpeed.MultiplyMoveSpeed_C.Execute
// 0x0078 (0x0078 - 0x0000)
struct MultiplyMoveSpeed_C_Execute final
{
public:
	struct FM1AbilityOpCalcParam                  Param;                                             // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
	struct FM1AbilityOpExecCalcOutput             Output;                                            // 0x0008(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FM1ScaledInteger                       CallFunc_FromFloat_ReturnValue;                    // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1StatTypeOpValue                     K2Node_MakeStruct_M1StatTypeOpValue;               // 0x0020(0x0010)(NoDestructor)
	struct FM1StatTypeOpValue                     K2Node_MakeStruct_M1StatTypeOpValue_1;             // 0x0030(0x0010)(NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FM1StatTypeOpValue                     K2Node_MakeStruct_M1StatTypeOpValue_2;             // 0x0048(0x0010)(NoDestructor)
	struct FM1StatTypeOpValue                     K2Node_MakeStruct_M1StatTypeOpValue_3;             // 0x0058(0x0010)(NoDestructor)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FromFloat_InValue_ImplicitCast;           // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MultiplyMoveSpeed_C_Execute) == 0x000008, "Wrong alignment on MultiplyMoveSpeed_C_Execute");
static_assert(sizeof(MultiplyMoveSpeed_C_Execute) == 0x000078, "Wrong size on MultiplyMoveSpeed_C_Execute");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, Param) == 0x000000, "Member 'MultiplyMoveSpeed_C_Execute::Param' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, Output) == 0x000008, "Member 'MultiplyMoveSpeed_C_Execute::Output' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_FromFloat_ReturnValue) == 0x000018, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_FromFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, K2Node_MakeStruct_M1StatTypeOpValue) == 0x000020, "Member 'MultiplyMoveSpeed_C_Execute::K2Node_MakeStruct_M1StatTypeOpValue' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, K2Node_MakeStruct_M1StatTypeOpValue_1) == 0x000030, "Member 'MultiplyMoveSpeed_C_Execute::K2Node_MakeStruct_M1StatTypeOpValue_1' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_Array_Add_ReturnValue) == 0x000040, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_Array_Add_ReturnValue_1) == 0x000044, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_Array_Add_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, K2Node_MakeStruct_M1StatTypeOpValue_2) == 0x000048, "Member 'MultiplyMoveSpeed_C_Execute::K2Node_MakeStruct_M1StatTypeOpValue_2' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, K2Node_MakeStruct_M1StatTypeOpValue_3) == 0x000058, "Member 'MultiplyMoveSpeed_C_Execute::K2Node_MakeStruct_M1StatTypeOpValue_3' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_Array_Add_ReturnValue_2) == 0x000068, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_Array_Add_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_Array_Add_ReturnValue_3) == 0x00006C, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_Array_Add_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(MultiplyMoveSpeed_C_Execute, CallFunc_FromFloat_InValue_ImplicitCast) == 0x000070, "Member 'MultiplyMoveSpeed_C_Execute::CallFunc_FromFloat_InValue_ImplicitCast' has a wrong offset!");

}

