#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NPC_VoidFusion

#include "Basic.hpp"

#include "NPC_VoidFusion_classes.hpp"
#include "NPC_VoidFusion_parameters.hpp"


namespace SDK
{

// Function NPC_VoidFusion.NPC_VoidFusion_C.ExecuteUbergraph_NPC_VoidFusion
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_VoidFusion_C::ExecuteUbergraph_NPC_VoidFusion(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_VoidFusion_C", "ExecuteUbergraph_NPC_VoidFusion");

	Params::NPC_VoidFusion_C_ExecuteUbergraph_NPC_VoidFusion Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_VoidFusion.NPC_VoidFusion_C.ReceiveActorBeginOverlap
// (Event, Public, BlueprintEvent)
// Parameters:
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ANPC_VoidFusion_C::ReceiveActorBeginOverlap(class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_VoidFusion_C", "ReceiveActorBeginOverlap");

	Params::NPC_VoidFusion_C_ReceiveActorBeginOverlap Parms{};

	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function NPC_VoidFusion.NPC_VoidFusion_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ANPC_VoidFusion_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_VoidFusion_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function NPC_VoidFusion.NPC_VoidFusion_C.ReceiveTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ANPC_VoidFusion_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("NPC_VoidFusion_C", "ReceiveTick");

	Params::NPC_VoidFusion_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}

}

