#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ReactorAbilityBase

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass ReactorAbilityBase.ReactorAbilityBase_C
// 0x0008 (0x02A8 - 0x02A0)
class UReactorAbilityBase_C : public UM1Ability
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void BP_OnActivated();
	void BP_OnDeactivated(bool bCancelled);
	void ExecuteUbergraph_ReactorAbilityBase(int32 EntryPoint);
	void ProcessOptimize();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ReactorAbilityBase_C">();
	}
	static class UReactorAbilityBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UReactorAbilityBase_C>();
	}
};
static_assert(alignof(UReactorAbilityBase_C) == 0x000008, "Wrong alignment on UReactorAbilityBase_C");
static_assert(sizeof(UReactorAbilityBase_C) == 0x0002A8, "Wrong size on UReactorAbilityBase_C");
static_assert(offsetof(UReactorAbilityBase_C, UberGraphFrame) == 0x0002A0, "Member 'UReactorAbilityBase_C::UberGraphFrame' has a wrong offset!");

}

