#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_EquipAltWeapon

#include "Basic.hpp"

#include "M1Data_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "M1_structs.hpp"


namespace SDK::Params
{

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.BP_OnDeactivated
// 0x0001 (0x0001 - 0x0000)
struct Skill_EquipAltWeapon_C_BP_OnDeactivated final
{
public:
	bool                                          bCancelled;                                        // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_BP_OnDeactivated) == 0x000001, "Wrong alignment on Skill_EquipAltWeapon_C_BP_OnDeactivated");
static_assert(sizeof(Skill_EquipAltWeapon_C_BP_OnDeactivated) == 0x000001, "Wrong size on Skill_EquipAltWeapon_C_BP_OnDeactivated");
static_assert(offsetof(Skill_EquipAltWeapon_C_BP_OnDeactivated, bCancelled) == 0x000000, "Member 'Skill_EquipAltWeapon_C_BP_OnDeactivated::bCancelled' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.CanReceiveEndInput
// 0x0001 (0x0001 - 0x0000)
struct Skill_EquipAltWeapon_C_CanReceiveEndInput final
{
public:
	bool                                          Return;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_CanReceiveEndInput) == 0x000001, "Wrong alignment on Skill_EquipAltWeapon_C_CanReceiveEndInput");
static_assert(sizeof(Skill_EquipAltWeapon_C_CanReceiveEndInput) == 0x000001, "Wrong size on Skill_EquipAltWeapon_C_CanReceiveEndInput");
static_assert(offsetof(Skill_EquipAltWeapon_C_CanReceiveEndInput, Return) == 0x000000, "Member 'Skill_EquipAltWeapon_C_CanReceiveEndInput::Return' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.CustomTryCommitActivateCost
// 0x0002 (0x0002 - 0x0000)
struct Skill_EquipAltWeapon_C_CustomTryCommitActivateCost final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TryCommitActivateCost_ReturnValue;        // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_CustomTryCommitActivateCost) == 0x000001, "Wrong alignment on Skill_EquipAltWeapon_C_CustomTryCommitActivateCost");
static_assert(sizeof(Skill_EquipAltWeapon_C_CustomTryCommitActivateCost) == 0x000002, "Wrong size on Skill_EquipAltWeapon_C_CustomTryCommitActivateCost");
static_assert(offsetof(Skill_EquipAltWeapon_C_CustomTryCommitActivateCost, Result) == 0x000000, "Member 'Skill_EquipAltWeapon_C_CustomTryCommitActivateCost::Result' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_CustomTryCommitActivateCost, CallFunc_TryCommitActivateCost_ReturnValue) == 0x000001, "Member 'Skill_EquipAltWeapon_C_CustomTryCommitActivateCost::CallFunc_TryCommitActivateCost_ReturnValue' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.ExecuteUbergraph_Skill_EquipAltWeapon
// 0x04B8 (0x04B8 - 0x0000)
struct Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanReceiveEndInput_Return;                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           Temp_struct_Variable;                              // 0x0008(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           Temp_struct_Variable_1;                            // 0x0010(0x0008)(NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_2;                        // 0x0018(0x0040)(ConstParm)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate;              // 0x0058(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        Temp_struct_Variable_2;                            // 0x0068(0x0040)()
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue;             // 0x00A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEventData_WeaponSlotType     CallFunc_GetAbilityEventData_WeaponSlotType_ReturnValue; // 0x00B8(0x0010)()
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x00C8(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DA[0x2];                                       // 0x00DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           K2Node_Select_Default;                             // 0x00DC(0x0008)(NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_1;                        // 0x00E8(0x0040)(ConstParm)
	struct FM1AbilityEvent                        Temp_struct_Variable_3;                            // 0x0128(0x0040)()
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue_1;           // 0x0168(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0170(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_171[0x7];                                      // 0x0171(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1WeaponActivatedEventData*            K2Node_DynamicCast_AsM1Weapon_Activated_Event_Data; // 0x0178(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0180(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_181[0x3];                                      // 0x0181(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_2;            // 0x0184(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0194(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_195[0x3];                                      // 0x0195(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event;                          // 0x0198(0x0040)(ConstParm)
	struct FM1AbilityEvent                        Temp_struct_Variable_4;                            // 0x01D8(0x0040)()
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue_2;           // 0x0218(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0220(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_221[0x7];                                      // 0x0221(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1WeaponActionStateEventData*          K2Node_DynamicCast_AsM1Weapon_Action_State_Event_Data; // 0x0228(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0230(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_231[0x3];                                      // 0x0231(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0234(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0248(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        Temp_struct_Variable_5;                            // 0x0250(0x0040)()
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0290(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue;                 // 0x0291(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_292[0x6];                                      // 0x0292(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_4;                        // 0x0298(0x0040)(ConstParm)
	bool                                          K2Node_Event_bCancelled;                           // 0x02D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2D9[0x7];                                      // 0x02D9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_1;              // 0x02E0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_1;               // 0x02E9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2EA[0x6];                                      // 0x02EA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityId                           CallFunc_InvokeFirstStatusEffectToSelfByTag_ReturnValue; // 0x02F0(0x0010)(HasGetValueTypeHash)
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_4;            // 0x0300(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0310(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x0311(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0312(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_313[0x5];                                      // 0x0313(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_LocalWaitInput*          CallFunc_LocalWaitInput_ReturnValue;               // 0x0318(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0320(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_321[0x7];                                      // 0x0321(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue_3;           // 0x0328(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1AbilityEvent                        Temp_struct_Variable_6;                            // 0x0330(0x0040)()
	bool                                          CallFunc_IsValid_ReturnValue_7;                    // 0x0370(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0371(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_372[0x6];                                      // 0x0372(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FM1AbilityEvent                        K2Node_CustomEvent_Event_3;                        // 0x0378(0x0040)(ConstParm)
	struct FM1AbilityOwnerInfo                    CallFunc_GetOwnerInfo_ReturnValue;                 // 0x03B8(0x0038)(ConstParm, NoDestructor, ContainsInstancedReference)
	struct FM1AbilityEvent                        K2Node_MakeStruct_M1AbilityEvent;                  // 0x03F0(0x0040)()
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_2;              // 0x0430(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	TScriptInterface<class IM1AbilityEventInterface> CallFunc_HandleAbilityEvent_self_CastInput;        // 0x0438(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_HandleAbilityEvent_ReturnValue;           // 0x0448(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_8;                    // 0x044C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_2;               // 0x044D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44E[0x2];                                      // 0x044E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_WaitDelay*               CallFunc_WaitDelay_ReturnValue;                    // 0x0450(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_3;              // 0x0458(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_2;    // 0x0460(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_9;                    // 0x0461(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_462[0x2];                                      // 0x0462(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FM1AbilityEvent& Event)> K2Node_CreateDelegate_OutputDelegate_5;            // 0x0464(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_10;                   // 0x0474(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_475[0x3];                                      // 0x0475(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_6;            // 0x0478(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_4;              // 0x0488(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChangeWithAltWeapon_ReturnValue;       // 0x0490(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_TryExecuteCostOperation_ReturnValue;   // 0x0491(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_492[0x6];                                      // 0x0492(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue_5;              // 0x0498(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BP_TryStartOperationsToSelfByTag_ReturnValue; // 0x04A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_11;                   // 0x04A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_HasAuthority_ReturnValue_3;               // 0x04A2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4A3[0x5];                                      // 0x04A3(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1AbilityTask_WaitAbilityEvent*        CallFunc_WaitAbilityEvent_ReturnValue_4;           // 0x04A8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_12;                   // 0x04B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EM1EquipmentSlotType                          CallFunc_GetLastItemWeaponSlotType_ReturnValue;    // 0x04B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CustomTryCommitActivateCost_Result;       // 0x04B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x04B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanReceiveEndInput_Return_1;              // 0x04B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon");
static_assert(sizeof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon) == 0x0004B8, "Wrong size on Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, EntryPoint) == 0x000000, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::EntryPoint' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_CanReceiveEndInput_Return) == 0x000004, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_CanReceiveEndInput_Return' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_bool_Variable) == 0x000005, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable) == 0x000008, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_1) == 0x000010, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CustomEvent_Event_2) == 0x000018, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CustomEvent_Event_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate) == 0x000058, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_2) == 0x000068, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitAbilityEvent_ReturnValue) == 0x0000A8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitAbilityEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue) == 0x0000B0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetAbilityEventData_WeaponSlotType_ReturnValue) == 0x0000B8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetAbilityEventData_WeaponSlotType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000C8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x0000D8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ByteByte_ReturnValue_1) == 0x0000D9, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ByteByte_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_Select_Default) == 0x0000DC, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CustomEvent_Event_1) == 0x0000E8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CustomEvent_Event_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_3) == 0x000128, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitAbilityEvent_ReturnValue_1) == 0x000168, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitAbilityEvent_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_1) == 0x000170, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_DynamicCast_AsM1Weapon_Activated_Event_Data) == 0x000178, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_DynamicCast_AsM1Weapon_Activated_Event_Data' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_DynamicCast_bSuccess) == 0x000180, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_2) == 0x000184, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ByteByte_ReturnValue_2) == 0x000194, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ByteByte_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CustomEvent_Event) == 0x000198, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CustomEvent_Event' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_4) == 0x0001D8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitAbilityEvent_ReturnValue_2) == 0x000218, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitAbilityEvent_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_2) == 0x000220, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_DynamicCast_AsM1Weapon_Action_State_Event_Data) == 0x000228, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_DynamicCast_AsM1Weapon_Action_State_Event_Data' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_DynamicCast_bSuccess_1) == 0x000230, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_3) == 0x000234, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue) == 0x000248, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_5) == 0x000250, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_5' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_3) == 0x000290, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HasAuthority_ReturnValue) == 0x000291, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HasAuthority_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CustomEvent_Event_4) == 0x000298, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CustomEvent_Event_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_Event_bCancelled) == 0x0002D8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_Event_bCancelled' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue_1) == 0x0002E0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_4) == 0x0002E8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HasAuthority_ReturnValue_1) == 0x0002E9, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HasAuthority_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_InvokeFirstStatusEffectToSelfByTag_ReturnValue) == 0x0002F0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_InvokeFirstStatusEffectToSelfByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_4) == 0x000300, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ObjectObject_ReturnValue) == 0x000310, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ObjectObject_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_5) == 0x000311, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000312, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_LocalWaitInput_ReturnValue) == 0x000318, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_LocalWaitInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_6) == 0x000320, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitAbilityEvent_ReturnValue_3) == 0x000328, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitAbilityEvent_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, Temp_struct_Variable_6) == 0x000330, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::Temp_struct_Variable_6' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_7) == 0x000370, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ObjectObject_ReturnValue_1) == 0x000371, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ObjectObject_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CustomEvent_Event_3) == 0x000378, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CustomEvent_Event_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerInfo_ReturnValue) == 0x0003B8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_MakeStruct_M1AbilityEvent) == 0x0003F0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_MakeStruct_M1AbilityEvent' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue_2) == 0x000430, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HandleAbilityEvent_self_CastInput) == 0x000438, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HandleAbilityEvent_self_CastInput' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HandleAbilityEvent_ReturnValue) == 0x000448, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HandleAbilityEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_8) == 0x00044C, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_8' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HasAuthority_ReturnValue_2) == 0x00044D, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HasAuthority_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitDelay_ReturnValue) == 0x000450, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitDelay_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue_3) == 0x000458, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_EqualEqual_ObjectObject_ReturnValue_2) == 0x000460, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_EqualEqual_ObjectObject_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_9) == 0x000461, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_9' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_5) == 0x000464, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_10) == 0x000474, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_10' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, K2Node_CreateDelegate_OutputDelegate_6) == 0x000478, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::K2Node_CreateDelegate_OutputDelegate_6' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue_4) == 0x000488, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_CanChangeWithAltWeapon_ReturnValue) == 0x000490, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_CanChangeWithAltWeapon_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_BP_TryExecuteCostOperation_ReturnValue) == 0x000491, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_BP_TryExecuteCostOperation_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetOwnerActor_ReturnValue_5) == 0x000498, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetOwnerActor_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_BP_TryStartOperationsToSelfByTag_ReturnValue) == 0x0004A0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_BP_TryStartOperationsToSelfByTag_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_11) == 0x0004A1, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_11' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_HasAuthority_ReturnValue_3) == 0x0004A2, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_HasAuthority_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_WaitAbilityEvent_ReturnValue_4) == 0x0004A8, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_WaitAbilityEvent_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsValid_ReturnValue_12) == 0x0004B0, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsValid_ReturnValue_12' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_GetLastItemWeaponSlotType_ReturnValue) == 0x0004B1, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_GetLastItemWeaponSlotType_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_CustomTryCommitActivateCost_Result) == 0x0004B2, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_CustomTryCommitActivateCost_Result' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_IsLocallyControlled_ReturnValue) == 0x0004B3, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon, CallFunc_CanReceiveEndInput_Return_1) == 0x0004B4, "Member 'Skill_EquipAltWeapon_C_ExecuteUbergraph_Skill_EquipAltWeapon::CallFunc_CanReceiveEndInput_Return_1' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.InitializeRounds
// 0x0018 (0x0018 - 0x0000)
struct Skill_EquipAltWeapon_C_InitializeRounds final
{
public:
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FM1ScaledInteger                       CallFunc_GetStatValue_StatValue;                   // 0x0008(0x0008)(NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetStatValue_ReturnValue;                 // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Conv_ScaledIntToInt_ReturnValue;          // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_InitializeRounds) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_InitializeRounds");
static_assert(sizeof(Skill_EquipAltWeapon_C_InitializeRounds) == 0x000018, "Wrong size on Skill_EquipAltWeapon_C_InitializeRounds");
static_assert(offsetof(Skill_EquipAltWeapon_C_InitializeRounds, CallFunc_GetOwnerActor_ReturnValue) == 0x000000, "Member 'Skill_EquipAltWeapon_C_InitializeRounds::CallFunc_GetOwnerActor_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_InitializeRounds, CallFunc_GetStatValue_StatValue) == 0x000008, "Member 'Skill_EquipAltWeapon_C_InitializeRounds::CallFunc_GetStatValue_StatValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_InitializeRounds, CallFunc_GetStatValue_ReturnValue) == 0x000010, "Member 'Skill_EquipAltWeapon_C_InitializeRounds::CallFunc_GetStatValue_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_InitializeRounds, CallFunc_Conv_ScaledIntToInt_ReturnValue) == 0x000014, "Member 'Skill_EquipAltWeapon_C_InitializeRounds::CallFunc_Conv_ScaledIntToInt_ReturnValue' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1
// 0x0040 (0x0040 - 0x0000)
struct Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1) == 0x000040, "Wrong size on Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1, Event) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnAbilityEvent_10B32DC54687DE7B021D50AD6DFA14F1::Event' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnAbilityEvent_209C47A242A4371A04A3EB98B9979174
// 0x0040 (0x0040 - 0x0000)
struct Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174) == 0x000040, "Wrong size on Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174, Event) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnAbilityEvent_209C47A242A4371A04A3EB98B9979174::Event' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789
// 0x0040 (0x0040 - 0x0000)
struct Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789) == 0x000040, "Wrong size on Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789, Event) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnAbilityEvent_A0B05E1C4F6F33B8D84A67BE19EB1789::Event' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE
// 0x0040 (0x0040 - 0x0000)
struct Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE) == 0x000040, "Wrong size on Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE, Event) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnAbilityEvent_F807D9B84912A3952D6DA8801D1102CE::Event' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17
// 0x0040 (0x0040 - 0x0000)
struct Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17 final
{
public:
	struct FM1AbilityEvent                        Event;                                             // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17) == 0x000040, "Wrong size on Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17, Event) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnAbilityEvent_F97548B44FDB4CFC1ACD57AF7F521D17::Event' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.OnChangedWeaponActionState
// 0x0018 (0x0018 - 0x0000)
struct Skill_EquipAltWeapon_C_OnChangedWeaponActionState final
{
public:
	class UM1WeaponActionStateEventData*          InEventData;                                       // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetWeaponCurrentRounds_ReturnValue;       // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_OnChangedWeaponActionState");
static_assert(sizeof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState) == 0x000018, "Wrong size on Skill_EquipAltWeapon_C_OnChangedWeaponActionState");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, InEventData) == 0x000000, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::InEventData' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000008, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000009, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_GetWeaponCurrentRounds_ReturnValue) == 0x00000C, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_GetWeaponCurrentRounds_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000010, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_BooleanAND_ReturnValue) == 0x000011, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_OnChangedWeaponActionState, CallFunc_BooleanAND_ReturnValue_1) == 0x000012, "Member 'Skill_EquipAltWeapon_C_OnChangedWeaponActionState::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.TryCommitAltWeaponCooltime
// 0x0001 (0x0001 - 0x0000)
struct Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime final
{
public:
	bool                                          CallFunc_TryCommitCooltime_ReturnValue;            // 0x0000(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime) == 0x000001, "Wrong alignment on Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime");
static_assert(sizeof(Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime) == 0x000001, "Wrong size on Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime");
static_assert(offsetof(Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime, CallFunc_TryCommitCooltime_ReturnValue) == 0x000000, "Member 'Skill_EquipAltWeapon_C_TryCommitAltWeaponCooltime::CallFunc_TryCommitCooltime_ReturnValue' has a wrong offset!");

// Function Skill_EquipAltWeapon.Skill_EquipAltWeapon_C.CanActivateAbility
// 0x0010 (0x0010 - 0x0000)
struct Skill_EquipAltWeapon_C_CanActivateAbility final
{
public:
	const class AActor*                           InOwner;                                           // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanChangeWithAltWeapon_ReturnValue;       // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(Skill_EquipAltWeapon_C_CanActivateAbility) == 0x000008, "Wrong alignment on Skill_EquipAltWeapon_C_CanActivateAbility");
static_assert(sizeof(Skill_EquipAltWeapon_C_CanActivateAbility) == 0x000010, "Wrong size on Skill_EquipAltWeapon_C_CanActivateAbility");
static_assert(offsetof(Skill_EquipAltWeapon_C_CanActivateAbility, InOwner) == 0x000000, "Member 'Skill_EquipAltWeapon_C_CanActivateAbility::InOwner' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_CanActivateAbility, ReturnValue) == 0x000008, "Member 'Skill_EquipAltWeapon_C_CanActivateAbility::ReturnValue' has a wrong offset!");
static_assert(offsetof(Skill_EquipAltWeapon_C_CanActivateAbility, CallFunc_CanChangeWithAltWeapon_ReturnValue) == 0x000009, "Member 'Skill_EquipAltWeapon_C_CanActivateAbility::CallFunc_CanChangeWithAltWeapon_ReturnValue' has a wrong offset!");

}

