#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Skill_Evade

#include "Basic.hpp"

#include "Skill_Evade_classes.hpp"
#include "Skill_Evade_parameters.hpp"


namespace SDK
{

// Function Skill_Evade.Skill_Evade_C.AxisMoveSmoothingOnReached
// (Public, BlueprintCallable, BlueprintEvent)

void USkill_Evade_C::AxisMoveSmoothingOnReached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "AxisMoveSmoothingOnReached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Evade.Skill_Evade_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void USkill_Evade_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Skill_Evade.Skill_Evade_C.BP_OnDeactivated
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bCancelled                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::BP_OnDeactivated(bool bCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "BP_OnDeactivated");

	Params::Skill_Evade_C_BP_OnDeactivated Parms{};

	Parms.bCancelled = bCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.ConvertDegreeTo8Direction
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  Angle                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UAnimMontage*                     OutMontage                                             (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::ConvertDegreeTo8Direction(double Angle, class UAnimMontage** OutMontage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "ConvertDegreeTo8Direction");

	Params::Skill_Evade_C_ConvertDegreeTo8Direction Parms{};

	Parms.Angle = Angle;

	UObject::ProcessEvent(Func, &Parms);

	if (OutMontage != nullptr)
		*OutMontage = Parms.OutMontage;
}


// Function Skill_Evade.Skill_Evade_C.ExecuteUbergraph_Skill_Evade
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::ExecuteUbergraph_Skill_Evade(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "ExecuteUbergraph_Skill_Evade");

	Params::Skill_Evade_C_ExecuteUbergraph_Skill_Evade Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.GetEvadeAnimLength
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  OutLength                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::GetEvadeAnimLength(double* OutLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "GetEvadeAnimLength");

	Params::Skill_Evade_C_GetEvadeAnimLength Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutLength != nullptr)
		*OutLength = Parms.OutLength;
}


// Function Skill_Evade.Skill_Evade_C.GetEvadeRecoveryAnimLength
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  OutLength                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::GetEvadeRecoveryAnimLength(double* OutLength)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "GetEvadeRecoveryAnimLength");

	Params::Skill_Evade_C_GetEvadeRecoveryAnimLength Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutLength != nullptr)
		*OutLength = Parms.OutLength;
}


// Function Skill_Evade.Skill_Evade_C.IsPlayerRunning
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bOutRunning                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::IsPlayerRunning(bool* bOutRunning)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "IsPlayerRunning");

	Params::Skill_Evade_C_IsPlayerRunning Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bOutRunning != nullptr)
		*bOutRunning = Parms.bOutRunning;
}


// Function Skill_Evade.Skill_Evade_C.IsRunning
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool                                    bRunning                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::IsRunning(bool* bRunning)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "IsRunning");

	Params::Skill_Evade_C_IsRunning Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bRunning != nullptr)
		*bRunning = Parms.bRunning;
}


// Function Skill_Evade.Skill_Evade_C.OnBlendOut_E0302FCF43DF0741F5CFC58FF67626CF
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Evade_C::OnBlendOut_E0302FCF43DF0741F5CFC58FF67626CF(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "OnBlendOut_E0302FCF43DF0741F5CFC58FF67626CF");

	Params::Skill_Evade_C_OnBlendOut_E0302FCF43DF0741F5CFC58FF67626CF Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.OnCompleted_E0302FCF43DF0741F5CFC58FF67626CF
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Evade_C::OnCompleted_E0302FCF43DF0741F5CFC58FF67626CF(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "OnCompleted_E0302FCF43DF0741F5CFC58FF67626CF");

	Params::Skill_Evade_C_OnCompleted_E0302FCF43DF0741F5CFC58FF67626CF Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.OnEventReceived_E0302FCF43DF0741F5CFC58FF67626CF
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FM1AbilityEvent                  Event                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USkill_Evade_C::OnEventReceived_E0302FCF43DF0741F5CFC58FF67626CF(const struct FM1AbilityEvent& Event)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "OnEventReceived_E0302FCF43DF0741F5CFC58FF67626CF");

	Params::Skill_Evade_C_OnEventReceived_E0302FCF43DF0741F5CFC58FF67626CF Parms{};

	Parms.Event = std::move(Event);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.OnFinished_6FE8C95042F333E7CBFD0ABF316AB07F
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    DestinationReached                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    TimedOut                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FVector                          FinalTargetLocation                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::OnFinished_6FE8C95042F333E7CBFD0ABF316AB07F(bool DestinationReached, bool TimedOut, const struct FVector& FinalTargetLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "OnFinished_6FE8C95042F333E7CBFD0ABF316AB07F");

	Params::Skill_Evade_C_OnFinished_6FE8C95042F333E7CBFD0ABF316AB07F Parms{};

	Parms.DestinationReached = DestinationReached;
	Parms.TimedOut = TimedOut;
	Parms.FinalTargetLocation = std::move(FinalTargetLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Skill_Evade.Skill_Evade_C.GetEvadeDistance
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// double                                  OutDistance                                            (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USkill_Evade_C::GetEvadeDistance(double* OutDistance) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "GetEvadeDistance");

	Params::Skill_Evade_C_GetEvadeDistance Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutDistance != nullptr)
		*OutDistance = Parms.OutDistance;
}


// Function Skill_Evade.Skill_Evade_C.MakeSkillActivateParams
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class AActor*                           InOwner                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TArray<struct FM1AbilityParamData>      ReturnValue                                            (Parm, OutParm, ReturnParm)

TArray<struct FM1AbilityParamData> USkill_Evade_C::MakeSkillActivateParams(const class AActor* InOwner) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Skill_Evade_C", "MakeSkillActivateParams");

	Params::Skill_Evade_C_MakeSkillActivateParams Parms{};

	Parms.InOwner = InOwner;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

