#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Button_Deco_Default_Dpad1_Deco

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Button_Deco_Default_Dpad1_Deco.UI_Button_Deco_Default_Dpad1_Deco_C
// 0x0020 (0x0728 - 0x0708)
class UUI_Button_Deco_Default_Dpad1_Deco_C final : public UM1UIWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0708(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       UIAnim_Loop;                                       // 0x0710(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Image_116;                                         // 0x0718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_218;                                         // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_Button_Deco_Default_Dpad1_Deco(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Button_Deco_Default_Dpad1_Deco_C">();
	}
	static class UUI_Button_Deco_Default_Dpad1_Deco_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Button_Deco_Default_Dpad1_Deco_C>();
	}
};
static_assert(alignof(UUI_Button_Deco_Default_Dpad1_Deco_C) == 0x000008, "Wrong alignment on UUI_Button_Deco_Default_Dpad1_Deco_C");
static_assert(sizeof(UUI_Button_Deco_Default_Dpad1_Deco_C) == 0x000728, "Wrong size on UUI_Button_Deco_Default_Dpad1_Deco_C");
static_assert(offsetof(UUI_Button_Deco_Default_Dpad1_Deco_C, UberGraphFrame) == 0x000708, "Member 'UUI_Button_Deco_Default_Dpad1_Deco_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_Button_Deco_Default_Dpad1_Deco_C, UIAnim_Loop) == 0x000710, "Member 'UUI_Button_Deco_Default_Dpad1_Deco_C::UIAnim_Loop' has a wrong offset!");
static_assert(offsetof(UUI_Button_Deco_Default_Dpad1_Deco_C, Image_116) == 0x000718, "Member 'UUI_Button_Deco_Default_Dpad1_Deco_C::Image_116' has a wrong offset!");
static_assert(offsetof(UUI_Button_Deco_Default_Dpad1_Deco_C, Image_218) == 0x000720, "Member 'UUI_Button_Deco_Default_Dpad1_Deco_C::Image_218' has a wrong offset!");

}

