#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Customize_ItemDetails

#include "Basic.hpp"

#include "UI_Customize_ItemDetails_classes.hpp"
#include "UI_Customize_ItemDetails_parameters.hpp"


namespace SDK
{

// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.BP_ShowAttackType
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::BP_ShowAttackType(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "BP_ShowAttackType");

	Params::UI_Customize_ItemDetails_C_BP_ShowAttackType Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.BP_ShowDescImpl
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::BP_ShowDescImpl(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "BP_ShowDescImpl");

	Params::UI_Customize_ItemDetails_C_BP_ShowDescImpl Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.BP_ShowPaints
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::BP_ShowPaints(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "BP_ShowPaints");

	Params::UI_Customize_ItemDetails_C_BP_ShowPaints Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.BP_ShowSkin
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::BP_ShowSkin(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "BP_ShowSkin");

	Params::UI_Customize_ItemDetails_C_BP_ShowSkin Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.ExecuteUbergraph_UI_Customize_ItemDetails
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::ExecuteUbergraph_UI_Customize_ItemDetails(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "ExecuteUbergraph_UI_Customize_ItemDetails");

	Params::UI_Customize_ItemDetails_C_ExecuteUbergraph_UI_Customize_ItemDetails Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.OnEventWidgetOpen
// (Event, Protected, BlueprintEvent)
// Parameters:
// EM1WidgetAnimDirection                  InDirection                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::OnEventWidgetOpen(EM1WidgetAnimDirection InDirection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "OnEventWidgetOpen");

	Params::UI_Customize_ItemDetails_C_OnEventWidgetOpen Parms{};

	Parms.InDirection = InDirection;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "PreConstruct");

	Params::UI_Customize_ItemDetails_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.SetDataImpl
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UM1UIData*                        InData                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::SetDataImpl(class UM1UIData* InData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "SetDataImpl");

	Params::UI_Customize_ItemDetails_C_SetDataImpl Parms{};

	Parms.InData = InData;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Customize_ItemDetails.UI_Customize_ItemDetails_C.ShowItemTier
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UM1UIDataItemInfo*                ItemInfo                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Customize_ItemDetails_C::ShowItemTier(class UM1UIDataItemInfo* ItemInfo)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Customize_ItemDetails_C", "ShowItemTier");

	Params::UI_Customize_ItemDetails_C_ShowItemTier Parms{};

	Parms.ItemInfo = ItemInfo;

	UObject::ProcessEvent(Func, &Parms);
}

}

