#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Crosshair_Scope_SCR_1003_Zoomed

#include "Basic.hpp"

#include "UI_Crosshair_Scope_SCR_0000_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Crosshair_Scope_SCR_1003_Zoomed.UI_Crosshair_Scope_SCR_1003_Zoomed_C
// 0x0000 (0x07C0 - 0x07C0)
class UUI_Crosshair_Scope_SCR_1003_Zoomed_C final : public UUI_Crosshair_Scope_SCR_0000_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Crosshair_Scope_SCR_1003_Zoomed_C">();
	}
	static class UUI_Crosshair_Scope_SCR_1003_Zoomed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Crosshair_Scope_SCR_1003_Zoomed_C>();
	}
};
static_assert(alignof(UUI_Crosshair_Scope_SCR_1003_Zoomed_C) == 0x000008, "Wrong alignment on UUI_Crosshair_Scope_SCR_1003_Zoomed_C");
static_assert(sizeof(UUI_Crosshair_Scope_SCR_1003_Zoomed_C) == 0x0007C0, "Wrong size on UUI_Crosshair_Scope_SCR_1003_Zoomed_C");

}

