#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_DialogPanel

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_DialogPanel.UI_DialogPanel_C
// 0x0018 (0x0788 - 0x0770)
class UUI_DialogPanel_C final : public UM1UIDialogPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0770(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               ForUIAlign;                                        // 0x0778(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Dialog_C*                           UI_Dialog;                                         // 0x0780(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_SetInCinematicSequencer(bool InbCinematic);
	void Construct();
	void ExecuteUbergraph_UI_DialogPanel(int32 EntryPoint);

	class UM1UIDialog* BP_GetDialogWidget() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_DialogPanel_C">();
	}
	static class UUI_DialogPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_DialogPanel_C>();
	}
};
static_assert(alignof(UUI_DialogPanel_C) == 0x000008, "Wrong alignment on UUI_DialogPanel_C");
static_assert(sizeof(UUI_DialogPanel_C) == 0x000788, "Wrong size on UUI_DialogPanel_C");
static_assert(offsetof(UUI_DialogPanel_C, UberGraphFrame) == 0x000770, "Member 'UUI_DialogPanel_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_DialogPanel_C, ForUIAlign) == 0x000778, "Member 'UUI_DialogPanel_C::ForUIAlign' has a wrong offset!");
static_assert(offsetof(UUI_DialogPanel_C, UI_Dialog) == 0x000780, "Member 'UUI_DialogPanel_C::UI_Dialog' has a wrong offset!");

}

