#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_InteractionObject_Marker

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_InteractionObject_Marker.UI_InteractionObject_Marker_C
// 0x0000 (0x0708 - 0x0708)
class UUI_InteractionObject_Marker_C final : public UM1UIWidget
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_InteractionObject_Marker_C">();
	}
	static class UUI_InteractionObject_Marker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_InteractionObject_Marker_C>();
	}
};
static_assert(alignof(UUI_InteractionObject_Marker_C) == 0x000008, "Wrong alignment on UUI_InteractionObject_Marker_C");
static_assert(sizeof(UUI_InteractionObject_Marker_C) == 0x000708, "Wrong size on UUI_InteractionObject_Marker_C");

}

