#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ItemIcon_Reactor

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ItemIcon_Reactor.UI_ItemIcon_Reactor_C
// 0x0078 (0x0780 - 0x0708)
class UUI_ItemIcon_Reactor_C final : public UM1UIWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0708(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWrapBox*                               Enchant_Track;                                     // 0x0710(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C;                        // 0x0718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_0;                      // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_1;                      // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_2;                      // 0x0730(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_3;                      // 0x0738(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_4;                      // 0x0740(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_5;                      // 0x0748(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_6;                      // 0x0750(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_ItemIcon_Reactor_Node_C*            UI_ItemIcon_Reactor_Node_C_7;                      // 0x0758(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	EOrientation                                  SetOrientation;                                    // 0x0760(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_761[0x3];                                      // 0x0761(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector2D                              SetNodeSize;                                       // 0x0764(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              SetNodePadding;                                    // 0x076C(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ViewBgDeco;                                        // 0x0774(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ViewNodeEffect;                                    // 0x0775(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_776[0x2];                                      // 0x0776(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CurrentLevel;                                      // 0x0778(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_UI_ItemIcon_Reactor(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void SetEnchantLevel(int32 Level, int32 MaxLevel, int32 Targetlevel);
	void SetUIStyel();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ItemIcon_Reactor_C">();
	}
	static class UUI_ItemIcon_Reactor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ItemIcon_Reactor_C>();
	}
};
static_assert(alignof(UUI_ItemIcon_Reactor_C) == 0x000008, "Wrong alignment on UUI_ItemIcon_Reactor_C");
static_assert(sizeof(UUI_ItemIcon_Reactor_C) == 0x000780, "Wrong size on UUI_ItemIcon_Reactor_C");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UberGraphFrame) == 0x000708, "Member 'UUI_ItemIcon_Reactor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, Enchant_Track) == 0x000710, "Member 'UUI_ItemIcon_Reactor_C::Enchant_Track' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C) == 0x000718, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_0) == 0x000720, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_0' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_1) == 0x000728, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_1' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_2) == 0x000730, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_2' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_3) == 0x000738, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_3' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_4) == 0x000740, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_4' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_5) == 0x000748, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_5' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_6) == 0x000750, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_6' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, UI_ItemIcon_Reactor_Node_C_7) == 0x000758, "Member 'UUI_ItemIcon_Reactor_C::UI_ItemIcon_Reactor_Node_C_7' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, SetOrientation) == 0x000760, "Member 'UUI_ItemIcon_Reactor_C::SetOrientation' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, SetNodeSize) == 0x000764, "Member 'UUI_ItemIcon_Reactor_C::SetNodeSize' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, SetNodePadding) == 0x00076C, "Member 'UUI_ItemIcon_Reactor_C::SetNodePadding' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, ViewBgDeco) == 0x000774, "Member 'UUI_ItemIcon_Reactor_C::ViewBgDeco' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, ViewNodeEffect) == 0x000775, "Member 'UUI_ItemIcon_Reactor_C::ViewNodeEffect' has a wrong offset!");
static_assert(offsetof(UUI_ItemIcon_Reactor_C, CurrentLevel) == 0x000778, "Member 'UUI_ItemIcon_Reactor_C::CurrentLevel' has a wrong offset!");

}

