#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ItemIcon_RandomOption_Node

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "M1Data_structs.hpp"


namespace SDK::Params
{

// Function UI_ItemIcon_RandomOption_Node.UI_ItemIcon_RandomOption_Node_C.ExecuteUbergraph_UI_ItemIcon_RandomOption_Node
// 0x0008 (0x0008 - 0x0000)
struct UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node) == 0x000004, "Wrong alignment on UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node");
static_assert(sizeof(UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node) == 0x000008, "Wrong size on UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node");
static_assert(offsetof(UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node, EntryPoint) == 0x000000, "Member 'UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node, K2Node_Event_IsDesignTime) == 0x000004, "Member 'UI_ItemIcon_RandomOption_Node_C_ExecuteUbergraph_UI_ItemIcon_RandomOption_Node::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_ItemIcon_RandomOption_Node.UI_ItemIcon_RandomOption_Node_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_ItemIcon_RandomOption_Node_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ItemIcon_RandomOption_Node_C_PreConstruct) == 0x000001, "Wrong alignment on UI_ItemIcon_RandomOption_Node_C_PreConstruct");
static_assert(sizeof(UI_ItemIcon_RandomOption_Node_C_PreConstruct) == 0x000001, "Wrong size on UI_ItemIcon_RandomOption_Node_C_PreConstruct");
static_assert(offsetof(UI_ItemIcon_RandomOption_Node_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_ItemIcon_RandomOption_Node_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function UI_ItemIcon_RandomOption_Node.UI_ItemIcon_RandomOption_Node_C.SetRandomOptionTier
// 0x0014 (0x0014 - 0x0000)
struct UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier final
{
public:
	EM1ItemOptionTierType                         Tier;                                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FLinearColor                           CallFunc_Get_UI_ItemOptionTierColor_DeepColors_TierColor; // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier) == 0x000004, "Wrong alignment on UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier");
static_assert(sizeof(UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier) == 0x000014, "Wrong size on UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier");
static_assert(offsetof(UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier, Tier) == 0x000000, "Member 'UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier::Tier' has a wrong offset!");
static_assert(offsetof(UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier, CallFunc_Get_UI_ItemOptionTierColor_DeepColors_TierColor) == 0x000004, "Member 'UI_ItemIcon_RandomOption_Node_C_SetRandomOptionTier::CallFunc_Get_UI_ItemOptionTierColor_DeepColors_TierColor' has a wrong offset!");

}

