#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Icon_Spinner_03

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_Icon_Spinner_03.UI_Icon_Spinner_03_C.ExecuteUbergraph_UI_Icon_Spinner_03
// 0x0018 (0x0018 - 0x0000)
struct UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03) == 0x000008, "Wrong alignment on UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03");
static_assert(sizeof(UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03) == 0x000018, "Wrong size on UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03");
static_assert(offsetof(UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03, EntryPoint) == 0x000000, "Member 'UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03, K2Node_Event_IsDesignTime) == 0x000010, "Member 'UI_Icon_Spinner_03_C_ExecuteUbergraph_UI_Icon_Spinner_03::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function UI_Icon_Spinner_03.UI_Icon_Spinner_03_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Icon_Spinner_03_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Icon_Spinner_03_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Icon_Spinner_03_C_PreConstruct");
static_assert(sizeof(UI_Icon_Spinner_03_C_PreConstruct) == 0x000001, "Wrong size on UI_Icon_Spinner_03_C_PreConstruct");
static_assert(offsetof(UI_Icon_Spinner_03_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Icon_Spinner_03_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

