#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_NeutralityPlayerList_Items

#include "Basic.hpp"

#include "M1_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_Mission_NeutralityPlayerList_Items.UI_Mission_NeutralityPlayerList_Items_C
// 0x0020 (0x0738 - 0x0718)
class UUI_Mission_NeutralityPlayerList_Items_C final : public UM1UIMissionWaveWaitingPlayerList
{
public:
	class UUI_Mission_NeutralityPlayerList_Item_C* UI_Mission_NeutralityPlayerListItem_1;             // 0x0718(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_NeutralityPlayerList_Item_C* UI_Mission_NeutralityPlayerListItem_2;             // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_NeutralityPlayerList_Item_C* UI_Mission_NeutralityPlayerListItem_3;             // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Mission_NeutralityPlayerList_Item_C* UI_Mission_NeutralityPlayerListItem_4;             // 0x0730(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_Mission_NeutralityPlayerList_Items_C">();
	}
	static class UUI_Mission_NeutralityPlayerList_Items_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_Mission_NeutralityPlayerList_Items_C>();
	}
};
static_assert(alignof(UUI_Mission_NeutralityPlayerList_Items_C) == 0x000008, "Wrong alignment on UUI_Mission_NeutralityPlayerList_Items_C");
static_assert(sizeof(UUI_Mission_NeutralityPlayerList_Items_C) == 0x000738, "Wrong size on UUI_Mission_NeutralityPlayerList_Items_C");
static_assert(offsetof(UUI_Mission_NeutralityPlayerList_Items_C, UI_Mission_NeutralityPlayerListItem_1) == 0x000718, "Member 'UUI_Mission_NeutralityPlayerList_Items_C::UI_Mission_NeutralityPlayerListItem_1' has a wrong offset!");
static_assert(offsetof(UUI_Mission_NeutralityPlayerList_Items_C, UI_Mission_NeutralityPlayerListItem_2) == 0x000720, "Member 'UUI_Mission_NeutralityPlayerList_Items_C::UI_Mission_NeutralityPlayerListItem_2' has a wrong offset!");
static_assert(offsetof(UUI_Mission_NeutralityPlayerList_Items_C, UI_Mission_NeutralityPlayerListItem_3) == 0x000728, "Member 'UUI_Mission_NeutralityPlayerList_Items_C::UI_Mission_NeutralityPlayerListItem_3' has a wrong offset!");
static_assert(offsetof(UUI_Mission_NeutralityPlayerList_Items_C, UI_Mission_NeutralityPlayerListItem_4) == 0x000730, "Member 'UUI_Mission_NeutralityPlayerList_Items_C::UI_Mission_NeutralityPlayerListItem_4' has a wrong offset!");

}

