#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Task_Invasion_HUDCenter

#include "Basic.hpp"

#include "UI_Mission_Task_Invasion_HUDCenter_classes.hpp"
#include "UI_Mission_Task_Invasion_HUDCenter_parameters.hpp"


namespace SDK
{

// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.BP_ShowWidget
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInShow                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Invasion_HUDCenter_C::BP_ShowWidget(bool bInShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "BP_ShowWidget");

	Params::UI_Mission_Task_Invasion_HUDCenter_C_BP_ShowWidget Parms{};

	Parms.bInShow = bInShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.BP_UpdateCollectionReturnState
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bInFullyCollected                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Invasion_HUDCenter_C::BP_UpdateCollectionReturnState(bool bInFullyCollected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "BP_UpdateCollectionReturnState");

	Params::UI_Mission_Task_Invasion_HUDCenter_C_BP_UpdateCollectionReturnState Parms{};

	Parms.bInFullyCollected = bInFullyCollected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Mission_Task_Invasion_HUDCenter_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.ExecuteUbergraph_UI_Mission_Task_Invasion_HUDCenter
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Invasion_HUDCenter_C::ExecuteUbergraph_UI_Mission_Task_Invasion_HUDCenter(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "ExecuteUbergraph_UI_Mission_Task_Invasion_HUDCenter");

	Params::UI_Mission_Task_Invasion_HUDCenter_C_ExecuteUbergraph_UI_Mission_Task_Invasion_HUDCenter Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.OnAnimFinished
// (BlueprintCallable, BlueprintEvent)

void UUI_Mission_Task_Invasion_HUDCenter_C::OnAnimFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "OnAnimFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.SequenceEvent
// (BlueprintCallable, BlueprintEvent)

void UUI_Mission_Task_Invasion_HUDCenter_C::SequenceEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "SequenceEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.SequenceEvent__ENTRYPOINTUI_Mission_Task_Invasion_HUDCenter
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Mission_Task_Invasion_HUDCenter_C::SequenceEvent__ENTRYPOINTUI_Mission_Task_Invasion_HUDCenter()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "SequenceEvent__ENTRYPOINTUI_Mission_Task_Invasion_HUDCenter");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.Set Sub Type
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// uint8                                   InSubType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Invasion_HUDCenter_C::Set_Sub_Type(uint8 InSubType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "Set Sub Type");

	Params::UI_Mission_Task_Invasion_HUDCenter_C_Set_Sub_Type Parms{};

	Parms.InSubType = InSubType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Invasion_HUDCenter.UI_Mission_Task_Invasion_HUDCenter_C.SetDataImpl
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UM1UIData*                        InData                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Invasion_HUDCenter_C::SetDataImpl(class UM1UIData* InData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Invasion_HUDCenter_C", "SetDataImpl");

	Params::UI_Mission_Task_Invasion_HUDCenter_C_SetDataImpl Parms{};

	Parms.InData = InData;

	UObject::ProcessEvent(Func, &Parms);
}

}

