#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_EliteAbilityDetails_Items

#include "Basic.hpp"

#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function UI_Mission_EliteAbilityDetails_Items.UI_Mission_EliteAbilityDetails_Items_C.ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items
// 0x000C (0x000C - 0x0000)
struct UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items) == 0x000004, "Wrong alignment on UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items");
static_assert(sizeof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items) == 0x00000C, "Wrong size on UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, EntryPoint) == 0x000000, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, Temp_bool_Variable) == 0x000004, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, Temp_byte_Variable) == 0x000005, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, Temp_byte_Variable_1) == 0x000006, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, K2Node_Event_IsDesignTime) == 0x000007, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::K2Node_Event_IsDesignTime' has a wrong offset!");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items, K2Node_Select_Default) == 0x000008, "Member 'UI_Mission_EliteAbilityDetails_Items_C_ExecuteUbergraph_UI_Mission_EliteAbilityDetails_Items::K2Node_Select_Default' has a wrong offset!");

// Function UI_Mission_EliteAbilityDetails_Items.UI_Mission_EliteAbilityDetails_Items_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct UI_Mission_EliteAbilityDetails_Items_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Mission_EliteAbilityDetails_Items_C_PreConstruct) == 0x000001, "Wrong alignment on UI_Mission_EliteAbilityDetails_Items_C_PreConstruct");
static_assert(sizeof(UI_Mission_EliteAbilityDetails_Items_C_PreConstruct) == 0x000001, "Wrong size on UI_Mission_EliteAbilityDetails_Items_C_PreConstruct");
static_assert(offsetof(UI_Mission_EliteAbilityDetails_Items_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'UI_Mission_EliteAbilityDetails_Items_C_PreConstruct::IsDesignTime' has a wrong offset!");

}

