#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_MapBattleZoneUnlockNoti

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_MapBattleZoneUnlockNoti.UI_MapBattleZoneUnlockNoti_C
// 0x0018 (0x0778 - 0x0760)
class UUI_MapBattleZoneUnlockNoti_C final : public UM1UIGame_MapBattleZoneUnlockNoti
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0760(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UM1TextBlock*                           Text_BattleZoneDesc;                               // 0x0768(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UM1TextBlock*                           Text_Title;                                        // 0x0770(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_widget_playAkEvent(class UAkAudioEvent* AkEvent);
	void ExecuteUbergraph_UI_MapBattleZoneUnlockNoti(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTUI_MapBattleZoneUnlockNoti();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_MapBattleZoneUnlockNoti_C">();
	}
	static class UUI_MapBattleZoneUnlockNoti_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_MapBattleZoneUnlockNoti_C>();
	}
};
static_assert(alignof(UUI_MapBattleZoneUnlockNoti_C) == 0x000008, "Wrong alignment on UUI_MapBattleZoneUnlockNoti_C");
static_assert(sizeof(UUI_MapBattleZoneUnlockNoti_C) == 0x000778, "Wrong size on UUI_MapBattleZoneUnlockNoti_C");
static_assert(offsetof(UUI_MapBattleZoneUnlockNoti_C, UberGraphFrame) == 0x000760, "Member 'UUI_MapBattleZoneUnlockNoti_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_MapBattleZoneUnlockNoti_C, Text_BattleZoneDesc) == 0x000768, "Member 'UUI_MapBattleZoneUnlockNoti_C::Text_BattleZoneDesc' has a wrong offset!");
static_assert(offsetof(UUI_MapBattleZoneUnlockNoti_C, Text_Title) == 0x000770, "Member 'UUI_MapBattleZoneUnlockNoti_C::Text_Title' has a wrong offset!");

}

