#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_CheckPointTime_Item

#include "Basic.hpp"

#include "UI_Mission_CheckPointTime_Item_classes.hpp"
#include "UI_Mission_CheckPointTime_Item_parameters.hpp"


namespace SDK
{

// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.BP_ChangeButtonUI
// (Event, Public, BlueprintEvent)
// Parameters:
// EM1ButtonUIType                         InType                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::BP_ChangeButtonUI(EM1ButtonUIType InType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "BP_ChangeButtonUI");

	Params::UI_Mission_CheckPointTime_Item_C_BP_ChangeButtonUI Parms{};

	Parms.InType = InType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.BP_ChangeDimmedUI
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    InDimmed                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::BP_ChangeDimmedUI(const bool InDimmed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "BP_ChangeDimmedUI");

	Params::UI_Mission_CheckPointTime_Item_C_BP_ChangeDimmedUI Parms{};

	Parms.InDimmed = InDimmed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.BP_Selected
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    InSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::BP_Selected(bool InSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "BP_Selected");

	Params::UI_Mission_CheckPointTime_Item_C_BP_Selected Parms{};

	Parms.InSelected = InSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.BP_UpdatePlayerList
// (Event, Protected, BlueprintEvent)

void UUI_Mission_CheckPointTime_Item_C::BP_UpdatePlayerList()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "BP_UpdatePlayerList");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.Change Selected UI
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::Change_Selected_UI(bool InSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "Change Selected UI");

	Params::UI_Mission_CheckPointTime_Item_C_Change_Selected_UI Parms{};

	Parms.InSelected = InSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.ChangeButtonUI
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// EM1ButtonUIType                         InType                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::ChangeButtonUI(EM1ButtonUIType InType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "ChangeButtonUI");

	Params::UI_Mission_CheckPointTime_Item_C_ChangeButtonUI Parms{};

	Parms.InType = InType;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_Mission_CheckPointTime_Item_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.ExecuteUbergraph_UI_Mission_CheckPointTime_Item
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::ExecuteUbergraph_UI_Mission_CheckPointTime_Item(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "ExecuteUbergraph_UI_Mission_CheckPointTime_Item");

	Params::UI_Mission_CheckPointTime_Item_C_ExecuteUbergraph_UI_Mission_CheckPointTime_Item Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "PreConstruct");

	Params::UI_Mission_CheckPointTime_Item_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.SetUIDefault
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsStop                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::SetUIDefault(bool IsStop)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "SetUIDefault");

	Params::UI_Mission_CheckPointTime_Item_C_SetUIDefault Parms{};

	Parms.IsStop = IsStop;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.ShowDimmedUI
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bShow                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_CheckPointTime_Item_C::ShowDimmedUI(bool bShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "ShowDimmedUI");

	Params::UI_Mission_CheckPointTime_Item_C_ShowDimmedUI Parms{};

	Parms.bShow = bShow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_CheckPointTime_Item.UI_Mission_CheckPointTime_Item_C.UpdateBG
// (Public, BlueprintCallable, BlueprintEvent)

void UUI_Mission_CheckPointTime_Item_C::UpdateBG()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_CheckPointTime_Item_C", "UpdateBG");

	UObject::ProcessEvent(Func, nullptr);
}

}

