#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Task_Interaction

#include "Basic.hpp"

#include "UI_Mission_Task_Interaction_classes.hpp"
#include "UI_Mission_Task_Interaction_parameters.hpp"


namespace SDK
{

// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.BP_ExplodedTarget
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bExploded                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::BP_ExplodedTarget(int32 Index_0, bool bExploded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "BP_ExplodedTarget");

	Params::UI_Mission_Task_Interaction_C_BP_ExplodedTarget Parms{};

	Parms.Index_0 = Index_0;
	Parms.bExploded = bExploded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.BP_SetInfoString
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FString                           InString                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::BP_SetInfoString(const class FString& InString)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "BP_SetInfoString");

	Params::UI_Mission_Task_Interaction_C_BP_SetInfoString Parms{};

	Parms.InString = std::move(InString);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.BP_SetTargetCount
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Count                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::BP_SetTargetCount(int32 Count)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "BP_SetTargetCount");

	Params::UI_Mission_Task_Interaction_C_BP_SetTargetCount Parms{};

	Parms.Count = Count;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.BP_SetTargetInfo
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   Index_0                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FString                           StringId                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// class FString                           SymbolStringId                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::BP_SetTargetInfo(int32 Index_0, const class FString& StringId, const class FString& SymbolStringId)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "BP_SetTargetInfo");

	Params::UI_Mission_Task_Interaction_C_BP_SetTargetInfo Parms{};

	Parms.Index_0 = Index_0;
	Parms.StringId = std::move(StringId);
	Parms.SymbolStringId = std::move(SymbolStringId);

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.ExecuteUbergraph_UI_Mission_Task_Interaction
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::ExecuteUbergraph_UI_Mission_Task_Interaction(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "ExecuteUbergraph_UI_Mission_Task_Interaction");

	Params::UI_Mission_Task_Interaction_C_ExecuteUbergraph_UI_Mission_Task_Interaction Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_Mission_Task_Interaction.UI_Mission_Task_Interaction_C.GetTargetWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   InIndex                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UM1UIWidget*                      Object                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UUI_Mission_Task_Interaction_C::GetTargetWidget(int32 InIndex, class UM1UIWidget** Object)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_Mission_Task_Interaction_C", "GetTargetWidget");

	Params::UI_Mission_Task_Interaction_C_GetTargetWidget Parms{};

	Parms.InIndex = InIndex;

	UObject::ProcessEvent(Func, &Parms);

	if (Object != nullptr)
		*Object = Parms.Object;
}

}

