#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_Mission_Task_DeathEvasion_HudCenter

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_Mission_Task_DeathEvasion_HudCenter.UI_Mission_Task_DeathEvasion_HudCenter_C.ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter
// 0x0028 (0x0028 - 0x0000)
struct UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsAnimationPlaying_ReturnValue;           // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UM1UIData*                              K2Node_Event_InData;                               // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UM1UIDataTaskDeathEvasionInfo*          K2Node_DynamicCast_AsM1UIData_Task_Death_Evasion_Info; // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_ShouldLimitTimeWarnIfBelow_ReturnValue;   // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x6];                                       // 0x001A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayUIAnimation_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter) == 0x000008, "Wrong alignment on UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter");
static_assert(sizeof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter) == 0x000028, "Wrong size on UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, EntryPoint) == 0x000000, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::EntryPoint' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, CallFunc_IsAnimationPlaying_ReturnValue) == 0x000004, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::CallFunc_IsAnimationPlaying_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, K2Node_Event_InData) == 0x000008, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::K2Node_Event_InData' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, K2Node_DynamicCast_AsM1UIData_Task_Death_Evasion_Info) == 0x000010, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::K2Node_DynamicCast_AsM1UIData_Task_Death_Evasion_Info' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, K2Node_DynamicCast_bSuccess) == 0x000018, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, CallFunc_ShouldLimitTimeWarnIfBelow_ReturnValue) == 0x000019, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::CallFunc_ShouldLimitTimeWarnIfBelow_ReturnValue' has a wrong offset!");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter, CallFunc_PlayUIAnimation_ReturnValue) == 0x000020, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_ExecuteUbergraph_UI_Mission_Task_DeathEvasion_HudCenter::CallFunc_PlayUIAnimation_ReturnValue' has a wrong offset!");

// Function UI_Mission_Task_DeathEvasion_HudCenter.UI_Mission_Task_DeathEvasion_HudCenter_C.SetDataImpl
// 0x0008 (0x0008 - 0x0000)
struct UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl final
{
public:
	class UM1UIData*                              InData;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl) == 0x000008, "Wrong alignment on UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl");
static_assert(sizeof(UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl) == 0x000008, "Wrong size on UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl");
static_assert(offsetof(UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl, InData) == 0x000000, "Member 'UI_Mission_Task_DeathEvasion_HudCenter_C_SetDataImpl::InData' has a wrong offset!");

}

