#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_NPC_Overhead

#include "Basic.hpp"


namespace SDK::Params
{

// Function UI_NPC_Overhead.UI_NPC_Overhead_C.ExecuteUbergraph_UI_NPC_Overhead
// 0x0004 (0x0004 - 0x0000)
struct UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead) == 0x000004, "Wrong alignment on UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead");
static_assert(sizeof(UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead) == 0x000004, "Wrong size on UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead");
static_assert(offsetof(UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead, EntryPoint) == 0x000000, "Member 'UI_NPC_Overhead_C_ExecuteUbergraph_UI_NPC_Overhead::EntryPoint' has a wrong offset!");

}

