#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_PerkList

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_PerkList.UI_PerkList_C
// 0x0038 (0x0750 - 0x0718)
class UUI_PerkList_C final : public UM1UIPerkList
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0718(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UOverlay*                               P_PerkList;                                        // 0x0720(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Perk_Panel;                                        // 0x0728(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_PerkListItem_C*                     UI_PerkListItem_00;                                // 0x0730(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	int32                                         IconSize;                                          // 0x0738(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                UI_PerkListPadding;                                // 0x073C(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_UI_PerkList(int32 EntryPoint);
	void PerkWidgetOffIfHasNoPerk(class UM1UIData* InData);
	void PreConstruct(bool IsDesignTime);
	void SetDataImpl(class UM1UIData* InData);
	void SetPanelAlign();
	void SetPerkItemSize();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_PerkList_C">();
	}
	static class UUI_PerkList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_PerkList_C>();
	}
};
static_assert(alignof(UUI_PerkList_C) == 0x000008, "Wrong alignment on UUI_PerkList_C");
static_assert(sizeof(UUI_PerkList_C) == 0x000750, "Wrong size on UUI_PerkList_C");
static_assert(offsetof(UUI_PerkList_C, UberGraphFrame) == 0x000718, "Member 'UUI_PerkList_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_PerkList_C, P_PerkList) == 0x000720, "Member 'UUI_PerkList_C::P_PerkList' has a wrong offset!");
static_assert(offsetof(UUI_PerkList_C, Perk_Panel) == 0x000728, "Member 'UUI_PerkList_C::Perk_Panel' has a wrong offset!");
static_assert(offsetof(UUI_PerkList_C, UI_PerkListItem_00) == 0x000730, "Member 'UUI_PerkList_C::UI_PerkListItem_00' has a wrong offset!");
static_assert(offsetof(UUI_PerkList_C, IconSize) == 0x000738, "Member 'UUI_PerkList_C::IconSize' has a wrong offset!");
static_assert(offsetof(UUI_PerkList_C, UI_PerkListPadding) == 0x00073C, "Member 'UUI_PerkList_C::UI_PerkListPadding' has a wrong offset!");

}

