#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_StatusEffect_Notice

#include "Basic.hpp"

#include "UI_StatusEffect_Notice_classes.hpp"
#include "UI_StatusEffect_Notice_parameters.hpp"


namespace SDK
{

// Function UI_StatusEffect_Notice.UI_StatusEffect_Notice_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UUI_StatusEffect_Notice_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StatusEffect_Notice_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_StatusEffect_Notice.UI_StatusEffect_Notice_C.ExecuteUbergraph_UI_StatusEffect_Notice
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_StatusEffect_Notice_C::ExecuteUbergraph_UI_StatusEffect_Notice(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StatusEffect_Notice_C", "ExecuteUbergraph_UI_StatusEffect_Notice");

	Params::UI_StatusEffect_Notice_C_ExecuteUbergraph_UI_StatusEffect_Notice Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UI_StatusEffect_Notice.UI_StatusEffect_Notice_C.FinishedAnimation
// (BlueprintCallable, BlueprintEvent)

void UUI_StatusEffect_Notice_C::FinishedAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StatusEffect_Notice_C", "FinishedAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function UI_StatusEffect_Notice.UI_StatusEffect_Notice_C.InitWidget
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bBoss                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUI_StatusEffect_Notice_C::InitWidget(bool bBoss)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UI_StatusEffect_Notice_C", "InitWidget");

	Params::UI_StatusEffect_Notice_C_InitWidget Parms{};

	Parms.bBoss = bBoss;

	UObject::ProcessEvent(Func, &Parms);
}

}

