#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UI_ToastMessage_BottomLineButton

#include "Basic.hpp"

#include "M1_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass UI_ToastMessage_BottomLineButton.UI_ToastMessage_BottomLineButton_C
// 0x0028 (0x07A0 - 0x0778)
class UUI_ToastMessage_BottomLineButton_C final : public UM1UIToastMessage_HoldButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0778(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Effect;                                            // 0x0780(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_108;                                         // 0x0788(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_1;                                         // 0x0790(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UUI_Deco_TitleLine_04_C*                UI_Deco_TitleLine_04;                              // 0x0798(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void ExecuteUbergraph_UI_ToastMessage_BottomLineButton(int32 EntryPoint);
	void SequenceEvent__ENTRYPOINTUI_ToastMessage_BottomLineButton();
	void UIplayakevent(class UAkAudioEvent* AkEvent);

	bool BP_IsVisibleToast() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UI_ToastMessage_BottomLineButton_C">();
	}
	static class UUI_ToastMessage_BottomLineButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUI_ToastMessage_BottomLineButton_C>();
	}
};
static_assert(alignof(UUI_ToastMessage_BottomLineButton_C) == 0x000008, "Wrong alignment on UUI_ToastMessage_BottomLineButton_C");
static_assert(sizeof(UUI_ToastMessage_BottomLineButton_C) == 0x0007A0, "Wrong size on UUI_ToastMessage_BottomLineButton_C");
static_assert(offsetof(UUI_ToastMessage_BottomLineButton_C, UberGraphFrame) == 0x000778, "Member 'UUI_ToastMessage_BottomLineButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UUI_ToastMessage_BottomLineButton_C, Effect) == 0x000780, "Member 'UUI_ToastMessage_BottomLineButton_C::Effect' has a wrong offset!");
static_assert(offsetof(UUI_ToastMessage_BottomLineButton_C, Image_108) == 0x000788, "Member 'UUI_ToastMessage_BottomLineButton_C::Image_108' has a wrong offset!");
static_assert(offsetof(UUI_ToastMessage_BottomLineButton_C, Overlay_1) == 0x000790, "Member 'UUI_ToastMessage_BottomLineButton_C::Overlay_1' has a wrong offset!");
static_assert(offsetof(UUI_ToastMessage_BottomLineButton_C, UI_Deco_TitleLine_04) == 0x000798, "Member 'UUI_ToastMessage_BottomLineButton_C::UI_Deco_TitleLine_04' has a wrong offset!");

}

